### ISSUE TITLE
Project licensing does not match licensing reported from arg_parser

### ISSUE THREAD

**Issue by tomc603** [cloudnull/AdvancedSearchDiscovery#2]
License reported here https://github.com/cloudnull/AdvancedSearchDiscovery/blob/master/asd/run.py#L34 is Apache 2.0, but the rest of the licensing is listed as GPL 3.

**Comment by d34dh0r53** [comment]
:+1: This affects me too

**Comment by prometheanfire** [comment]
:+1: this is a issue that's blocking us

**Comment by d34dh0r53** [comment]
:8ball:

**Comment by sigmavirus24** [comment]
:-1: Do not want

**Comment by d34dh0r53** [comment]
Can you :1234: and fix this?

**Comment by sigmavirus24** [comment]
:raised_hands:

**Comment by prometheanfire** [comment]
:abcd: :ABCD:
