### ISSUE TITLE
958ba5 breaks my workflow

### ISSUE THREAD

**Issue by sigmavirus24** [cloudnull/AdvancedSearchDiscovery#3]
Please revert 958ba512bfd908ee706528fc6513cf8091120c83

**Comment by sigmavirus24** [comment]
https://xkcd.com/1172/

**Comment by cloudnull** [comment]
your issue is really important to us, please hold for the next available person whom cares.

**Comment by sigmavirus24** [comment]
*who cares

**Comment by cloudnull** [comment]
:+1:
